Fix rs232_set_* prototypes mismatch
Fixes compilation error on gcc 13 (excerpt):
 rs232_posix.c:490:1: error: conflicting types for 'rs232_set_baud' \
   due to enum/integer mismatch; have 'unsigned int(struct rs232_port_t *, \
   enum rs232_baud_e)' [-Werror=enum-int-mismatch]
  490 | rs232_set_baud(struct rs232_port_t *p, enum rs232_baud_e baud)
      | ^~~~~~~~~~~~~~
 In file included from rs232_posix.c:39:
 ../include/librs232/rs232.h:203:24: note: previous declaration of \
   'rs232_set_baud' with type 'unsigned int(struct rs232_port_t *, unsigned int)'
  203 | RS232_LIB unsigned int rs232_set_baud(struct rs232_port_t *p, unsigned int baud);
      |                        ^~~~~~~~~~~~~~

 rs232_posix.c:591:1: error: conflicting types for 'rs232_set_dtr' \
  due to enum/integer mismatch; have 'unsigned int(struct rs232_port_t *, \
  enum rs232_dtr_e)' [-Werror=enum-int-mismatch]
  591 | rs232_set_dtr(struct rs232_port_t *p, enum rs232_dtr_e state)
      | ^~~~~~~~~~~~~
 In file included from rs232_posix.c:39:
  ../include/librs232/rs232.h:208:24: note: previous declaration of 'rs232_set_dtr' \
  with type 'unsigned int(struct rs232_port_t *, unsigned int)'
  208 | RS232_LIB unsigned int rs232_set_dtr(struct rs232_port_t *p, unsigned int dtr);
      |                        ^~~~~~~~~~~~~

Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>